{% set name = "socksio" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/socksio-{{ version }}.tar.gz
  sha256: f88beb3da5b5c38b9890469de67d0cb0f9d494b78b106ca1845f96c10b91c4ac

build:
  skip: True  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - flit-core >=2,<3
    - pip
  run:
    - python

test:
  imports:
    - socksio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sethmlarson/socksio
  summary: Sans-I/O implementation of SOCKS4, SOCKS4A, and SOCKS5.
  description: |
    socksio is a sans-I/O library similar to h11 or h2,
    this means the library itself does not handle the actual sending of the bytes
    through the network, it only deals with the implementation details
    of the SOCKS protocols so you can use it in any I/O library you want.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://pypi.org/project/socksio/
  dev_url: https://github.com/sethmlarson/socksio

extra:
  recipe-maintainers:
    - sodre
